# Generated by Django 3.2.4 on 2021-06-05 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('slug', models.CharField(blank=True, max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='about/')),
            ],
        ),
    ]
